"use client";
import { useEffect, useState, useCallback, useRef } from 'react';
import { Activity, ArrowUpRight, BarChart3, BookOpen, Check, ChevronRight, Clock3, ExternalLink, FlaskConical, Info, Newspaper, RefreshCw, Search, Sparkles, TrendingUp } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxEmpty } from '@/components/ui/combobox';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { STOCKS, STOCK_CATALOG, FEATURED_STOCKS, RANGES, type MarketData, type NewsData, type Sentiment, type Metric } from '@/lib/stocks';
import { stockSignal } from '@/lib/signal';
import evaluation from '@/lib/generated/evaluation.json';
import finbertEvaluation from '@/lib/generated/finbert-evaluation.json';

const percent = (n: number) => `${(n * 100).toFixed(1)}%`;
const format = (n: number | null | undefined, digits = 2) => n === null || n === undefined ? '—' : new Intl.NumberFormat('en-IN', { maximumFractionDigits: digits }).format(n);
const money = (n: number | null | undefined) => n === null || n === undefined ? '—' : `₹${format(n)}`;
const crore = (n: number | null | undefined) => n === null || n === undefined ? '—' : `₹${format(n / 1e7, 0)} Cr`;
const time = (s: string | null | undefined) => s ? new Date(s).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kolkata' }) + ' IST' : 'Not available';
const date = (s: string | null | undefined) => s ? new Date(s).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'Asia/Kolkata' }) : 'Not available';
function Badge({ label }: { label: string }) { return <span className={`badge ${label.toLowerCase().replace(/ /g, '-')}`}>{label}</span> }
function Empty({ text }: { text: string }) { return <div className="empty"><Info size={22} /><p>{text}</p></div> }
function MetricCard({ label, value, detail }: { label: string; value: string; detail?: string }) { return <div className="metric-card"><span>{label}</span><strong>{value}</strong><small>{detail || 'Unavailable from provider'}</small></div> }
async function getJson<T>(url: string, signal?: AbortSignal): Promise<T> { const r = await fetch(url, { signal }); if (!r.ok) throw new Error('Unable to load this data. Please try again.'); return r.json(); }

export default function Home() {
  const [tab, setTab] = useState('stocks');
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' }); }, [tab]);
  const [symbol, setSymbol] = useState('RELIANCE.NS');
  const [range, setRange] = useState('3M');
  const [market, setMarket] = useState<MarketData | null>(null);
  const [news, setNews] = useState<NewsData | null>(null);
  const [marketLoading, setMarketLoading] = useState(true), [newsLoading, setNewsLoading] = useState(true);
  const [marketError, setMarketError] = useState(''), [newsError, setNewsError] = useState('');
  const [refresh, setRefresh] = useState(0);
  const [filter, setFilter] = useState('all');
  const [stockSearch, setStockSearch] = useState('');
  const [modelStatus, setModelStatus] = useState('');
  const [headline, setHeadline] = useState('');
  const [analysedText, setAnalysedText] = useState('');
  const [result, setResult] = useState<Sentiment | null>(null);
  const [analysing, setAnalysing] = useState(false), [analysisError, setAnalysisError] = useState('');
  const analysisRequest = useRef(0);
  const stock = STOCKS.find(s => s.symbol === symbol)!;
  const matchingStocks = stockSearch.trim() ? STOCKS.filter(s => `${s.name} ${s.symbol}`.toLowerCase().includes(stockSearch.trim().toLowerCase())).slice(0, 60) : FEATURED_STOCKS;
  useEffect(() => { const id = setInterval(() => setRefresh(r => r + 1), 300000); return () => clearInterval(id); }, []);
  useEffect(() => {
    const controller = new AbortController(); setMarket(null); setMarketLoading(true); setMarketError('');
    getJson<MarketData>(`/api/market?symbol=${symbol}&range=${range}`, controller.signal).then(setMarket).catch(e => { if (e.name !== 'AbortError') setMarketError(e.message) }).finally(() => { if (!controller.signal.aborted) setMarketLoading(false) });
    return () => controller.abort();
  }, [symbol, range, refresh]);
  useEffect(() => {
    const controller = new AbortController(); setNews(null); setNewsLoading(true); setNewsError(''); setFilter('all');
    getJson<NewsData>(`/api/news?symbol=${symbol}`, controller.signal).then(async data => {
      if (!data.items.length) { if (!controller.signal.aborted) setNews(data); return; }
      try {
        const { classifyFinbert } = await import('@/lib/finbert-client');
        const predictions = await classifyFinbert(data.items.map(item => item.title), setModelStatus);
        if (!controller.signal.aborted) { setNews({ ...data, items: data.items.map((item, index) => ({ ...item, sentiment: predictions[index] })) }); setModelStatus('FinBERT ready'); }
      } catch (error) { if (!controller.signal.aborted) { setNews(data); setModelStatus('FinBERT unavailable — showing baseline sentiment'); console.warn('FinBERT news classification failed', error); } }
    }).catch(e => { if (e.name !== 'AbortError') setNewsError(e.message) }).finally(() => { if (!controller.signal.aborted) setNewsLoading(false) });
    return () => controller.abort();
  }, [symbol, refresh]);
  const analyse = useCallback(async (text: string) => {
    if (text.trim().length < 5 || text.length > 2000) { setAnalysisError('Enter a headline between 5 and 2,000 characters.'); throw new Error('Invalid headline length.'); }
    const request = ++analysisRequest.current; setAnalysing(true); setAnalysisError(''); setResult(null); setHeadline(text);
    try {
      let data: Sentiment;
      try { const { classifyFinbert } = await import('@/lib/finbert-client'); data = (await classifyFinbert([text], setModelStatus))[0]; setModelStatus('FinBERT ready'); }
      catch (error) { console.warn('FinBERT headline classification failed', error); const r = await fetch('/api/sentiment', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); data = await r.json() as Sentiment & { error?: string }; if (!r.ok) throw new Error((data as Sentiment & { error?: string }).error || 'Analysis failed.'); data.note = 'FinBERT is unavailable. Showing the TF-IDF baseline. ' + data.note; setModelStatus('FinBERT unavailable — showing baseline sentiment'); }
      if (request === analysisRequest.current) { setResult(data); setAnalysedText(text); } return data;
    } catch (e) { if (request === analysisRequest.current) setAnalysisError(e instanceof Error ? e.message : 'Analysis failed.'); throw e; } finally { if (request === analysisRequest.current) setAnalysing(false); }
  }, []);
  useEffect(() => {
    const context = (document as unknown as { modelContext?: { registerTool: (tool: unknown, options: unknown) => unknown } }).modelContext; if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try { Promise.resolve(context.registerTool({ name: 'analyse_financial_headline', description: 'Classify an English financial headline and display its sentiment in the headline checker.', inputSchema: { type: 'object', properties: { text: { type: 'string', minLength: 5, maxLength: 2000 } }, required: ['text'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: true }, execute: async (input: unknown) => { const text = (input as { text?: unknown })?.text; if (typeof text !== 'string' || text.trim().length < 5 || text.length > 2000) throw new Error('Enter a headline between 5 and 2,000 characters.'); setTab('headlines'); const r = await analyse(text); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); return { label: r.label, confidence: r.confidence, note: r.note }; } }, { signal: lifecycle.signal })).catch(() => { }); } catch { }
    return () => lifecycle.abort();
  }, [analyse]);
  const signal = stockSignal(market, news);
  const f = market?.fundamentals;
  const counts = { positive: 0, neutral: 0, negative: 0 };
  for (const item of news?.items || []) if (item.sentiment.label in counts) counts[item.sentiment.label as keyof typeof counts]++;
  const newsTotal = Object.values(counts).reduce((a, b) => a + b, 0);
  const visibleNews = news?.items.filter(n => filter === 'all' || n.sentiment.label === filter) || [];
  const lastPrice = market?.price;
  const periodStart = market?.history[0]?.close;
  const periodChange = lastPrice != null && periodStart ? (lastPrice / periodStart - 1) * 100 : null;
  const report = evaluation;
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="MarketScope home"><span className="brand-mark"><Activity size={23} /></span><span>Market<span className="brand-light">Scope</span></span><span className="india-tag">INDIA</span></a><div className="top-right"><span className="research-tag"><FlaskConical size={15} /> Research edition</span><span className="avatar">MS</span></div></header>
    <Tabs value={tab} onValueChange={setTab} className="workspace-tabs">
      <div className="nav-wrap"><TabsList className="main-nav" variant="line"><TabsTrigger value="stocks" onClick={() => setTab('stocks')}><BarChart3 size={17} />Stock overview</TabsTrigger><TabsTrigger value="headlines" onClick={() => setTab('headlines')}><Newspaper size={17} />Headline checker</TabsTrigger><TabsTrigger value="model" onClick={() => setTab('model')}><FlaskConical size={17} />Model & evaluation</TabsTrigger></TabsList><span className="nav-note">{STOCK_CATALOG.count.toLocaleString()} NSE equities · Catalog {date(STOCK_CATALOG.fetchedAt)}</span></div>
      <main className="main-content">
        <TabsContent value="stocks">
          <div className="page-heading"><div><div className="eyebrow">MARKET INTELLIGENCE</div><h1>The company. The numbers. The news.</h1><p>Explore financial performance alongside the sentiment behind recent headlines.</p></div><button className="button secondary" onClick={() => setRefresh(r => r + 1)} disabled={marketLoading || newsLoading}><RefreshCw size={16} className={marketLoading || newsLoading ? 'spin' : ''} />Refresh feeds</button></div>
          <div className="stock-toolbar"><div className="stock-picker"><Search size={18} /><Combobox items={matchingStocks} value={stock} onValueChange={v => { if (v) { setSymbol(v.symbol); setStockSearch('') } }} itemToStringLabel={s => `${s.name} · ${s.symbol.replace('.NS', '')}`}><ComboboxInput aria-label="Search NSE stock" placeholder="Search a company or symbol" onInput={e => setStockSearch((e.currentTarget as HTMLInputElement).value)} /><ComboboxContent><ComboboxEmpty>No listed NSE equity matches your search.</ComboboxEmpty><ComboboxList>{(s: typeof stock) => <ComboboxItem key={s.symbol} value={s}>{s.name}<span className="ticker-text">{s.symbol.replace('.NS', '')}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><div className="feed-note"><Clock3 size={15} />Feeds refresh every 5 minutes<span className="separator">/</span>Prices may be delayed</div></div>
          <div className="stock-title"><div className="company-monogram">{stock.name.split(' ').slice(0, 2).map(s => s[0]).join('')}</div><div><h2>{stock.name}<span className="exchange-tag">NSE</span></h2><p>{stock.symbol.replace('.NS', '')} <span>·</span> {stock.sector}</p></div><div className="stock-price"><strong>{marketLoading ? 'Loading…' : money(lastPrice)}</strong>{market?.change != null && <span className={market.change >= 0 ? 'positive-text' : 'negative-text'}>{market.change >= 0 ? '+' : ''}{format(market.change)}% <small>since prior close</small></span>}</div></div>
          {(marketError || market?.issues.length) ? <div className="notice" role="status"><Info size={17} />{marketError || market?.issues.join(' ')}</div> : null}
          <div className="metrics-grid"><MetricCard label="Market cap · estimated" value={crore(f?.marketCap.value)} detail={f?.marketCap.value != null ? `Reported shares × latest price · ${date(f.marketCap.asOf)}` : undefined} /><MetricCard label="P/E ratio · trailing" value={format(f?.pe.value)} detail={f?.pe.value != null ? `Price / diluted EPS · ${date(f.pe.asOf)}` : 'Not meaningful for negative EPS, or unavailable'} /><MetricCard label="Earnings per share · TTM" value={money(f?.eps.value)} detail={f?.eps.asOf ? `Period ending ${date(f.eps.asOf)}` : undefined} /><MetricCard label="52-week range" value={market?.low52 != null && market?.high52 != null ? `${format(market.low52, 0)} – ${format(market.high52, 0)}` : '—'} detail="INR · provider-reported price range" /></div>
          <div className="overview-grid">
            <section className="panel price-panel"><div className="panel-heading"><div><h3>Price performance</h3><p>{periodChange != null ? <><span className={periodChange >= 0 ? 'positive-text' : 'negative-text'}>{periodChange >= 0 ? '+' : ''}{format(periodChange)}%</span> over the selected period</> : 'Daily closing prices · INR'}</p></div><div className="period-buttons" aria-label="Chart period">{RANGES.map(r => <button key={r} aria-pressed={r === range} className={r === range ? 'active' : ''} onClick={() => setRange(r)}>{r}</button>)}</div></div>
              <div className="chart-area">{marketLoading ? <Empty text="Fetching price history…" /> : market?.history.length ? <ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{ width: 600, height: 270 }}><AreaChart data={market.history} margin={{ top: 18, right: 8, bottom: 8, left: 0 }}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7ce4a5" stopOpacity={.23} /><stop offset="100%" stopColor="#7ce4a5" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#27313e" strokeDasharray="3 6" /><XAxis dataKey="date" minTickGap={55} tickFormatter={s => new Date(s).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })} tick={{ fill: '#8f9aab', fontSize: 12 }} axisLine={false} tickLine={false} /><YAxis orientation="right" domain={['auto', 'auto']} tickFormatter={n => format(n, 0)} tick={{ fill: '#8f9aab', fontSize: 12 }} axisLine={false} tickLine={false} width={58} /><Tooltip contentStyle={{ background: '#182230', border: '1px solid #3d4c5d', borderRadius: 8, color: '#eef3f9' }} formatter={v => [money(Number(v)), 'Close']} labelFormatter={s => date(String(s))} /><Area type="monotone" dataKey="close" stroke="#83e7aa" strokeWidth={2.2} fill="url(#priceFill)" activeDot={{ r: 4 }} isAnimationActive={false} /></AreaChart></ResponsiveContainer> : <Empty text="Price history is unavailable. Refresh to try the provider again." />}</div>
              <div className="panel-footer"><span>Daily close · unadjusted</span><span>Price as of {time(market?.priceAt)}</span></div>
            </section>
            <section className="panel news-pulse"><div className="panel-heading"><div><h3>News sentiment</h3><p>Company headlines · last 7 days · {news?.items[0]?.sentiment.model || modelStatus || "FinBERT"}</p></div><Newspaper size={20} /></div><div className="pulse-total"><strong>{newsLoading ? '—' : newsTotal}</strong><span>headlines analysed</span></div><div className="sentiment-stack" aria-label="Sentiment distribution">{Object.entries(counts).map(([label, count]) => <div key={label} className={label} style={{ width: `${newsTotal ? count / newsTotal * 100 : 33.33}%` }} />)}</div><div className="pulse-legend">{Object.entries(counts).map(([label, count]) => <div key={label}><span><i className={label} />{label}</span><strong>{newsLoading ? '—' : count}</strong></div>)}</div><p className="small-note">Sentiment describes the headline.</p></section>
          </div>
          <div className="detail-grid"><section className="panel"><div className="panel-heading"><div><h3>Financial performance</h3><p>Reported quarterly results</p></div><BarChart3 size={20} /></div><div className="financial-summary"><div><span>Revenue growth · YoY</span><strong className={(f?.revenueGrowth.value || 0) >= 0 ? 'positive-text' : 'negative-text'}>{f?.revenueGrowth.value != null ? `${format(f.revenueGrowth.value)}%` : '—'}</strong></div><div><span>Profit growth · YoY</span><strong className={(f?.profitGrowth.value || 0) >= 0 ? 'positive-text' : 'negative-text'}>{f?.profitGrowth.value != null ? `${format(f.profitGrowth.value)}%` : '—'}</strong></div><div><span>Debt / equity</span><strong>{format(f?.debtEquity.value)}</strong></div><div><span>Return on equity</span><strong>{f?.roe.value != null ? `${format(f.roe.value)}%` : '—'}</strong></div></div>
            {f?.earnings.length ? <Table><TableHeader><TableRow><TableHead>Period ending</TableHead><TableHead className="right">Revenue</TableHead><TableHead className="right">Net profit</TableHead><TableHead className="right">EPS</TableHead></TableRow></TableHeader><TableBody>{[...f.earnings].reverse().map(e => <TableRow key={e.date}><TableCell>{date(e.date)}</TableCell><TableCell className="right">{crore(e.revenue)}</TableCell><TableCell className="right">{crore(e.netIncome)}</TableCell><TableCell className="right">{money(e.eps)}</TableCell></TableRow>)}</TableBody></Table> : <Empty text={marketLoading ? 'Fetching earnings…' : 'Quarterly results are unavailable for this company.'} />}
            <details className="method-details"><summary>Metric definitions and reporting dates</summary><p>TTM means trailing twelve months. Growth compares the latest quarter with the same quarter a year earlier. Debt/equity uses matched reporting dates; ROE uses trailing income divided by average annual equity. Missing or invalid ratios appear as a dash. Banking ratios need sector-specific interpretation.</p><p>Growth: {date(f?.profitGrowth.asOf)} · Debt/equity: {date(f?.debtEquity.asOf)} · ROE: {date(f?.roe.asOf)}. Latest provider records may have different reporting dates.</p></details>
          </section><section className="panel signal-panel"><div className="panel-heading"><div><h3>Research signal</h3><p>News + earnings + price trend</p></div><FlaskConical size={20} /></div><div className="signal-result"><Badge label={marketLoading || newsLoading ? 'Analysing' : signal.label} /><span>Experimental · not backtested</span></div><ul className="signal-reasons">{signal.reasons.map(r => <li key={r}><span className="reason-bullet" />{r}</li>)}</ul><details className="method-details"><summary>How this signal is calculated</summary><p>News contributes +1, 0 or −1 using recency-weighted positive minus negative probabilities (threshold ±0.15). Price above/below its 20-session average contributes +1/−1. Positive/nonpositive revenue and profit growth each contribute +1/−1. Score ≥3: Buy; ≤−3: Sell; otherwise Hold.</p><p>Requires recent prices, earnings, 20 trading sessions and three usable headlines from two publishers. Valuation is displayed separately and is not part of this simple rule. Thresholds have not been validated against future returns.</p></details><div className="signal-disclaimer"><Info size={16} /><span></span></div></section></div>
          <section className="panel feed-panel"><div className="panel-heading"><div><h3>Latest company news <span className="count-tag">{news?.items.length || 0}</span></h3><p>Fetched {time(news?.fetchedAt)} · duplicates filtered · headline-only analysis</p></div><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter news sentiment"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All sentiment</SelectItem><SelectItem value="positive">Positive</SelectItem><SelectItem value="neutral">Neutral</SelectItem><SelectItem value="negative">Negative</SelectItem></SelectContent></Select></div>
            {newsLoading ? <Empty text="Fetching recent company news…" /> : newsError || news?.issues.length ? <Empty text={newsError || news!.issues.join(' ')} /> : !visibleNews.length ? <Empty text="No headlines match this sentiment filter." /> : <div className="news-list">{visibleNews.map((n, i) => <article className="news-row" key={n.url}><span className="news-number">{String(i + 1).padStart(2, '0')}</span><div className="news-copy"><div className="news-meta"><span>{n.source}</span><span>·</span><time dateTime={n.publishedAt}>{time(n.publishedAt)}</time></div><a href={n.url} target="_blank" rel="noopener noreferrer">{n.title}<ArrowUpRight size={15} /></a></div><div className="news-label"><Badge label={n.sentiment.label} /><small>{n.sentiment.model || 'model'} · {n.sentiment.lowConfidence ? 'Uncertain prediction' : percent(n.sentiment.confidence)}</small></div></article>)}</div>}
            <div className="panel-footer"><span>Google News RSS · follow links to the publisher</span><button className="text-button" onClick={() => setTab('headlines')}>Analyse your own headline <ChevronRight size={15} /></button></div>
          </section>
          <p className="source-note">Market data: Yahoo Finance public endpoints, which may be delayed or unavailable. Refreshing checks the provider; it does not guarantee a new price. No simulated market values are used.</p>
        </TabsContent>
        <TabsContent value="headlines">
          <div className="page-heading"><div><div className="eyebrow">FINANCIAL LANGUAGE, DECODED</div><h1>What is the headline saying?</h1><p>Paste an English financial headline to classify its positive, neutral or negative sentiment.</p></div><span className="research-tag"><Sparkles size={16} />FinBERT · context-aware model</span></div>
          <div className="checker-grid"><section className="panel input-panel"><div className="panel-heading"><h3>Headline checker</h3><span className="muted">English</span></div><form onSubmit={e => { e.preventDefault(); void analyse(headline).catch(() => { }); }}><label htmlFor="headline">Enter a financial headline</label><textarea id="headline" value={headline} onChange={e => { setHeadline(e.target.value); analysisRequest.current++; setResult(null); setAnalysisError(''); setAnalysing(false); }} maxLength={2000} rows={6} placeholder="e.g. Company reports a sharp decline in quarterly profit" /><div className="input-footer"><span>{headline.length.toLocaleString()} / 2,000 characters</span><button className="button primary" type="submit" disabled={analysing || headline.trim().length < 5}>{analysing ? <RefreshCw size={16} className="spin" /> : <Sparkles size={16} />} {analysing ? 'Analysing…' : 'Analyse sentiment'}</button></div>{analysisError && <p className="error-text" role="alert">{analysisError}</p>}</form><div className="examples"><span>TRY AN EXAMPLE</span>{['Bank profits rise as loan growth accelerates', 'Company reports a sharp decline in quarterly profit', 'Company announces annual general meeting on Monday'].map(t => <button key={t} onClick={() => { void analyse(t).catch(() => { }); }} disabled={analysing}>{t}<ChevronRight size={16} /></button>)}</div><div className="small-note"><Info size={16} />This checks sentiment, not whether the headline is true.</div></section>
            <section className="panel prediction-panel" aria-live="polite"><div className="panel-heading"><h3>Analysis result</h3><span className="muted">{modelStatus || "FinBERT"}</span></div>{!result ? <div className="prediction-empty"><div className="prediction-icon"><Activity size={32} /></div><h3>{analysing ? 'Reading the financial language…' : 'A headline. Three possible signals.'}</h3><p>{analysing ? 'Applying the trained text classifier.' : 'Your classification, probability breakdown and model details will appear here.'}</p><div className="badge-row"><Badge label="positive" /><Badge label="neutral" /><Badge label="negative" /></div></div> : <div className="prediction-content"><blockquote>“{analysedText}”</blockquote><div className="prediction-label"><Badge label={result.label} />{result.relevant && <strong>{percent(result.confidence)}<small>model probability</small></strong>}</div>{result.relevant && <><div className="probability-bars">{['positive', 'neutral', 'negative'].map(label => <div key={label}><div><span>{label}</span><strong>{percent(result.probabilities[label])}</strong></div><div className="bar-track"><span className={label} style={{ width: `${result.probabilities[label] * 100}%` }} /></div></div>)}</div>{result.lowConfidence && <div className="notice"><Info size={16} />{result.model === 'FinBERT' ? 'Low confidence. Review the headline and source before interpreting this prediction.' : 'Low confidence or limited vocabulary coverage. Interpret this prediction cautiously.'}</div>}{result.evidence.length > 0 && <div className="evidence"><span className="eyebrow">INFLUENTIAL WORDS & PHRASES</span><div>{result.evidence.map(e => <span key={e.term}>{e.term}</span>)}</div><p>Features favouring this class over the runner-up; these are model contributions, not a factual explanation.</p></div>}</>}<p className="small-note">{result.note}</p></div>}</section></div>
          <div className="checker-foot"><div><BookOpen size={21} /><div><strong>{report.unique_count.toLocaleString()} financial examples</strong><span>Financial PhraseBank + Twitter Financial News</span></div></div><div><FlaskConical size={21} /><div><strong>{percent(report.macro_f1)} test macro-F1</strong><span>Baseline measured on {report.split_counts.test.toLocaleString()} held-out examples</span></div></div><button className="text-button" onClick={() => setTab('model')}>Explore the evaluation <ChevronRight size={16} /></button></div>
        </TabsContent>
        <TabsContent value="model">
          <div className="page-heading"><div><div className="eyebrow">TRANSPARENT BY DESIGN</div><h1>FinBERT and the baseline.</h1><p>FinBERT classifies live headlines. Both models were measured on the same independent Twitter Financial News holdout.</p></div><a className="button secondary" href="/api/evaluation/finbert" target="_blank" rel="noopener noreferrer"><ExternalLink size={16} />FinBERT evaluation JSON</a></div>
          <div className="metrics-grid"><MetricCard label="FinBERT macro-F1 · Twitter" value={percent(finbertEvaluation.macro_f1)} detail={`${finbertEvaluation.count.toLocaleString()} held-out examples`} /><MetricCard label="Baseline macro-F1 · Twitter" value={percent(report.source_results['Twitter Financial News'].macro_f1)} detail="Same 1,185 held-out examples" /><MetricCard label="FinBERT accuracy · Twitter" value={percent(finbertEvaluation.accuracy)} detail="Quantized ONNX model" /><MetricCard label="Clean baseline dataset" value={report.unique_count.toLocaleString()} detail={`${report.raw_count.toLocaleString()} raw examples · ${report.removed_count} removed`} /></div>
          <p className="small-note">FinBERT correctly labels the reported HDFC ADR spike positive, but its Twitter holdout macro-F1 is lower than the TF-IDF baseline. Neither result measures accuracy on independently labelled Indian company news. FinBERT was fine-tuned on Financial PhraseBank, so that dataset is excluded from the comparison.</p>
          <div className="detail-grid"><section className="panel"><div className="panel-heading"><div><h3>Baseline training data</h3><p>English financial text · three sentiment classes</p></div><BookOpen size={20} /></div><div className="dataset-card"><div><h4>Twitter Financial News</h4><span>{report.raw_source_counts['Twitter Financial News'].toLocaleString()} records · MIT</span></div><p>Finance-related posts labelled bearish, bullish or neutral. Mapped to negative, positive and neutral respectively.</p><a href="https://huggingface.co/datasets/zeroshot/twitter-financial-news-sentiment" target="_blank" rel="noopener noreferrer">Dataset and attribution <ExternalLink size={14} /></a></div><div className="dataset-card"><div><h4>Financial PhraseBank</h4><span>{report.raw_source_counts['Financial PhraseBank'].toLocaleString()} records · CC BY-NC-SA 3.0</span></div><p>Investor-oriented news sentences annotated by people with finance backgrounds. The greater-than-50% agreement subset is used once.</p><a href="https://huggingface.co/datasets/takala/financial_phrasebank" target="_blank" rel="noopener noreferrer">Dataset and attribution <ExternalLink size={14} /></a></div><p className="small-note dataset-note">Educational, noncommercial use. Source revisions and SHA-256 checksums are recorded in the evaluation JSON.</p></section>
            <section className="panel"><div className="panel-heading"><div><h3>How the baseline was evaluated</h3><p>Reproducible split · seed {report.seed}</p></div><FlaskConical size={20} /></div><ol className="method-list"><li><span>01</span><div><strong>Clean and group</strong><p>Remove duplicate and conflicting text. Group very similar headlines before splitting.</p></div></li><li><span>02</span><div><strong>Train / validate / test</strong><p>{report.split_counts.train.toLocaleString()} / {report.split_counts.validation.toLocaleString()} / {report.split_counts.test.toLocaleString()} examples. Grouped, stratified random folds.</p></div></li><li><span>03</span><div><strong>Learn text features</strong><p>{report.feature_count.toLocaleString()} TF-IDF words and two-word phrases, fitted only on training data. Balanced logistic regression.</p></div></li><li><span>04</span><div><strong>Select, then measure</strong><p>Choose regularisation on validation macro-F1, then evaluate the selected model once on the held-out test set.</p></div></li></ol></section></div>
          <div className="detail-grid"><section className="panel"><div className="panel-heading"><h3>Baseline per-class performance</h3></div><Table><TableHeader><TableRow><TableHead>Class</TableHead><TableHead>Precision</TableHead><TableHead>Recall</TableHead><TableHead>F1</TableHead><TableHead>Support</TableHead></TableRow></TableHeader><TableBody>{(['negative', 'neutral', 'positive'] as const).map(label => { const r = report.classification_report[label]; return <TableRow key={label}><TableCell><Badge label={label} /></TableCell><TableCell>{percent(r.precision)}</TableCell><TableCell>{percent(r.recall)}</TableCell><TableCell>{percent(r['f1-score'])}</TableCell><TableCell>{r.support}</TableCell></TableRow> })}</TableBody></Table><div className="panel-heading"><h3>Confusion matrix</h3><span className="muted">Rows: actual · columns: predicted</span></div><Table><TableHeader><TableRow><TableHead>Actual / predicted</TableHead>{report.labels.map(l => <TableHead key={l}>{l}</TableHead>)}</TableRow></TableHeader><TableBody>{report.confusion_matrix.map((row, i) => <TableRow key={i}><TableCell>{report.labels[i]}</TableCell>{row.map((n, j) => <TableCell className={i === j ? 'matrix-correct' : ''} key={j}>{n}</TableCell>)}</TableRow>)}</TableBody></Table></section><section className="panel limitations"><div className="panel-heading"><h3>What these results do—and don't—say</h3><Info size={20} /></div><ul>{report.limitations.map(l => <li key={l}>{l}</li>)}</ul><div className="next-benchmark"><strong>Next research milestone</strong><p>Independently label 300–500 Indian company headlines with two reviewers, then measure performance without retraining on that test set.</p></div></section></div>
        </TabsContent>
        <footer className="site-footer"><span><Activity size={15} />MarketScope <span>·</span> Financial sentiment research</span><span>Built for learning. Decisions need more than a headline.</span></footer>
      </main>
    </Tabs>
  </div>
}
